### ISSUE TITLE
Google search seems to block this extension somehow

### ISSUE THREAD

**Issue by lulu-berlin** [kerrizor/business_to_burrito#2]
![screenshot from 2017-01-02 18-05-09](https://cloud.githubusercontent.com/assets/10565807/21593320/14d39bca-d116-11e6-9e5d-a5a31b3a1065.png)

**Comment by kerrizor** [comment]
I wonder if it is a timing issue? 

https://github.com/kerrizor/business_to_burrito/blob/master/manifest.json#L17
```
"run_at": "document_end"
```

**Comment by kerrizor** [comment]
Yup.

> In the case of "document_end", the files are injected immediately after the DOM is complete, but before subresources like images and frames have loaded. 
https://developer.chrome.com/extensions/content_scripts

So I be what is happening for Google results page is the "page" loads, the burritoizer fires, and then the page *really* loads, via some action in Angular (becuase hey, if Google isn't using Angular, who is?)

The other values for `runs_at` don't seem to offer much improvement, so a solution is likely something along the lines of rescanning on every DOM change? Run a tick every second or two? I'm unfamiliar with current best practices for this sort of thing. If we rescan continually, some sort of limiter on the number of nodes scanned is likely to be useful.

**Comment by lulu-berlin** [comment]
Well, it makes sense that Google search is mutating the DOM. Don't know if they use Angular or something they created earlier before Angular existed (it is supposed to be supported by Internet Explorer, right?).

I think a timer function might be an overkill. It'll be best if the code could be optimized to run through the DOM the least possible.

So, there's the [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), that's supported since Chrome 18 (Feb 2012).

I also found [this](http://stackoverflow.com/questions/8882502/how-to-track-dom-change-in-chrome-extension) on StackOverflow, suggesting to use an event listener for DOMNodeInserted, but a more recent comment says it has been deprecated in favor of MutationObserver.

Should I try making a prototype?

**Comment by kerrizor** [comment]
@yever go for it!

**Comment by lulu-berlin** [comment]
So, here you go. 

MutationObserver is supported in Chrome since version 27 (Mar 28, 2013) and before that since version 18 (Feb 8, 2012) with the prefix `webkit-`. 

I can still add support for the prefix and maybe fallback to `setTimeout` for ancient versions. Right now the fallback is to the old replace once code.
